query Rooms {
	rooms {
		name
		seats
		handicap
		lab
		placesWithSocket
		exahm
		seb
		needsRequest
	}
	roomsForSlots {
		day
		slot
		rooms {
			name
			seats
			handicap
			lab
			placesWithSocket
			exahm
			seb
			needsRequest
		}
	}
}
